// Code generated by Kitex v0.4.4. DO NOT EDIT.

package interactsvr

import (
	"context"
	interact "dousheng/kitex_gen/interact"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Fav(ctx context.Context, Req *interact.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *interact.DouyinFavoriteActionResponse, err error)
	FavList(ctx context.Context, Req *interact.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *interact.DouyinFavoriteListResponse, err error)
	Comment(ctx context.Context, Req *interact.DouyinCommentActionRequest, callOptions ...callopt.Option) (r *interact.DouyinCommentActionResponse, err error)
	CommentList(ctx context.Context, Req *interact.DouyinCommentListRequest, callOptions ...callopt.Option) (r *interact.DouyinCommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractSvrClient struct {
	*kClient
}

func (p *kInteractSvrClient) Fav(ctx context.Context, Req *interact.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *interact.DouyinFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Fav(ctx, Req)
}

func (p *kInteractSvrClient) FavList(ctx context.Context, Req *interact.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *interact.DouyinFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavList(ctx, Req)
}

func (p *kInteractSvrClient) Comment(ctx context.Context, Req *interact.DouyinCommentActionRequest, callOptions ...callopt.Option) (r *interact.DouyinCommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Comment(ctx, Req)
}

func (p *kInteractSvrClient) CommentList(ctx context.Context, Req *interact.DouyinCommentListRequest, callOptions ...callopt.Option) (r *interact.DouyinCommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, Req)
}
