// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "tb_user"

// User mapped from table <tb_user>
type User struct {
	UserID        int64     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`              // 用户id
	Name          string    `gorm:"column:name" json:"name"`                                                  // 用户名
	FollowCount   int32     `gorm:"column:follow_count" json:"follow_count"`                                  // 关注总数
	FollowerCount int32     `gorm:"column:follower_count" json:"follower_count"`                              // 粉丝总数
	IsFollow      int32     `gorm:"column:is_follow" json:"is_follow"`                                        // 1:未关注,0:已关注
	Password      string    `gorm:"column:password" json:"password"`                                          // 密码
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
