// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "tb_message"

// Message mapped from table <tb_message>
type Message struct {
	MessageID  int64     `gorm:"column:message_id;primaryKey;autoIncrement:true" json:"message_id"`        // 消息id
	ToUserID   int64     `gorm:"column:to_user_id" json:"to_user_id"`                                      // 接收方id
	FromUserID int64     `gorm:"column:from_user_id" json:"from_user_id"`                                  // 发送方id
	Content    int32     `gorm:"column:content" json:"content"`                                            // 消息内容
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
